language: java
java:
  - openjdk7
  - openjdk8
  - oraclejdk8

runtime:
  nodePool: testARM

build:
  pre_ci_boot:
    image_name: drydockaarch64/u16javall
    image_tag: master
  ci:
    - java -verison


jobs:
  - name: java_test
    type: runSh
    runtime:
      nodePool: testARM
    steps:
      - TASK:
          name: java1
          runtime:
            options:
              imageName: drydockaarch64/u16javall
              imageTag: master
          script:
            - echo "update-alternatives --set java /usr/lib/jvm/java-7-openjdk-arm64/jre/bin/java"
            - update-alternatives --set java /usr/lib/jvm/java-7-openjdk-arm64/jre/bin/java
            - printf "\n===================================="
            - java -version
            - printf "\n===================================="
      - TASK:
          name: java2
          runtime:
            options:
              imageName: drydockaarch64/u16javall
              imageTag: master
          script:
            - echo "update-alternatives --set java /usr/lib/jvm/java-8-openjdk-arm64/jre/bin/java"
            - update-alternatives --set java /usr/lib/jvm/java-8-openjdk-arm64/jre/bin/java
            - printf "\n===================================="
            - java -version
            - printf "\n===================================="

      - TASK:
          name: java3
          runtime:
            options:
              imageName: drydockaarch64/u16javall
              imageTag: master
          script:
            - echo "update-alternatives --set java /usr/lib/jvm/java-8-oracle/jre/bin/java"
            - update-alternatives --set java /usr/lib/jvm/java-8-oracle/jre/bin/java
            - printf "\n===================================="
            - java -version
            - printf "\n===================================="
